#!/bin/bash

# Define instance IDs as variables
instance_id1="i-09f704de6ccbf1a6b"
instance_id2="i-09486ba0caef0749f"
instance_id3="i-0c40363490a5a04a4"
instance_id4="i-0dff1d5fe7732bc0c"

# Array of instance IDs
instance_ids=("$instance_id1" "$instance_id2" "$instance_id3" "$instance_id4")

# Loop through the instance IDs and stop each instance
for instance_id in "${instance_ids[@]}"; do
  echo "Stopping instance: $instance_id"
  aws ec2 stop-instances --instance-ids "$instance_id"
done

# Wait for instances to stop
for instance_id in "${instance_ids[@]}"; do
  echo "Waiting for instance $instance_id to stop..."
  aws ec2 wait instance-stopped --instance-ids "$instance_id"
done

# Check the status of instances after stopping
aws ec2 describe-instances --instance-ids "${instance_ids[@]}"

echo "Instances stopped successfully!"

